parameters:
#    footy_jokes_front.example.class: FootyJokes\FrontBundle\Example

services:
#    footy_jokes_front.example:
#        class: %footy_jokes_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
