footy_jokes_front:
    resource: "@FootyJokesFrontBundle/Resources/config/routing.yml"
    prefix:   /

footy_jokes_import:
    resource: "@FootyJokesImportBundle/Resources/config/routing.yml"
    prefix:   /import

footy_jokes_back:
    resource: "@FootyJokesBackBundle/Resources/config/routing.yml"
    prefix:   /admin

footy_jokes_api:
    resource: "@FootyJokesAPIBundle/Resources/config/routing.yml"
    prefix:   /api

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"