footy_jokes_import_homepage:
    pattern:  /
    defaults: { _controller: FootyJokesImportBundle:Default:index }

footy_jokes_import_twitter:
    pattern:  /twitter/timeline/{screenName}
    defaults: { _controller: FootyJokesImportBundle:Twitter:timeline }
