parameters:
#    footy_jokes_import.example.class: FootyJokes\ImportBundle\Example

services:
    footy_jokes_import.twitter:
      class:      FootyJokes\ImportBundle\Services\TwitterManager
      arguments:  ["@service_container"]
