footy_jokes_back_index:
    pattern:  /
    defaults: { _controller: FootyJokesBackBundle:Default:index }

footy_jokes_back_add_joke:
    pattern:  /joke/add
    defaults: { _controller: FootyJokesBackBundle:Joke:add }
    
footy_jokes_back_edit_joke:
    pattern:  /joke/edit/{id}/{page}
    defaults: { _controller: FootyJokesBackBundle:Joke:edit }

footy_jokes_back_joke_list:
    pattern:  /jokes/{page}
    defaults: { _controller: FootyJokesBackBundle:Joke:list, page: 1 }
