footy_jokes_back_add_joke:
    pattern:  /add
    defaults: { _controller: FootyJokesBackBundle:Joke:add }
    
footy_jokes_back_edit_joke:
    pattern:  /edit/{id}/{page}
    defaults: { _controller: FootyJokesBackBundle:Joke:edit }

footy_jokes_back_joke_list:
    pattern:  /jokes/{page}
    defaults: { _controller: FootyJokesBackBundle:Joke:list, page: 1 }
